import fetch from 'node-fetch'
import fs from 'fs'

let handler = async (m, { conn, command }) => {
  // 1) Lista de URLs de imágenes (modifica o amplía según tus necesidades)
  const imageUrls = [
    'https://pomf2.lain.la/f/heo0hfu6.jpg',
    'https://pomf2.lain.la/f/9yxhgs9j.jpg',
    'https://pomf2.lain.la/f/nqwlpdur.jpg',
    'https://pomf2.lain.la/f/mjns9r6n.jpg',
    'https://pomf2.lain.la/f/9wsnri0p.jpg'
  ]
  // Seleccionar una URL de imagen al azar
  const randomImageUrl = imageUrls[Math.floor(Math.random() * imageUrls.length)]

  // 2) Lista de 200 frases distintas (sin repeticiones)
  const responses = [
    "1) 💀 TK-HOST permanece firme, ni un huracán lo derriba.",
    "2) 🚀 Toma impulso: nuestros servidores están listos para despegar.",
    "3) 🤖 El hosting que entiende tu código, sin complicaciones.",
    "4) 🌐 Infraestructura global: tu proyecto se expande sin fronteras.",
    "5) 🛠️ Soporte 24/7: nos encanta resolver cualquier contratiempo.",
    "6) 📡 Conexión ultra estable: como un ancla en un mar tempestuoso.",
    "7) 🎉 Celebramos cada deploy exitoso, ¿te unes a la fiesta?",
    "8) 🔌 Servidores en línea: tu web jamás se quedará a oscuras.",
    "9) 📊 Monitoreo continuo: siempre vigilamos tu servicio.",
    "10) 🔥 Velocidad incandescente: tu sitio arderá de rendimiento.",
    "11) 💰 Invierte sabiamente: con TK-HOST pagas por calidad real.",
    "12) 🖥️ Tu panel de control: potencia en un par de clics.",
    "13) 🎮 Somos gamers: sabemos que la latencia es enemiga.",
    "14) 📦 Con TK-HOST, empaca tus ideas y lánzalas al mundo.",
    "15) 🔧 Configura, personaliza y domina: tú llevas el control.",
    "16) 🏆 A la vanguardia en tecnología: por eso somos la mejor opción.",
    "17) 🛒 Agrega un hosting a tu carrito y observa cómo crece tu proyecto.",
    "18) 💎 Seguridad diamantina: que nada interfiera con tu negocio.",
    "19) 🌟 Servicios de lujo a precios asequibles: eso es TK-HOST.",
    "20) 📈 Crecimiento garantizado: tu web despegará como cohete.",
    "21) 🔌 Pings mínimos: despídete de los retrasos.",
    "22) 💡 Ilumina tus ideas con un hosting que no falla.",
    "23) 🔒 Encriptación y seguridad para tus datos: duerme tranquilo.",
    "24) 🎯 Hosting al instante: y sin complicaciones en la instalación.",
    "25) 🌌 Alcance intergaláctico: tu sitio estará visible desde la Luna.",
    "26) 🌍 Soluciones en todos los continentes: conquista el planeta.",
    "27) 🤑 Ahorra con nuestras promociones, pero sin sacrificar calidad.",
    "28) 👑 Tu proyecto en un trono: nosotros lo coronamos con buen rendimiento.",
    "29) 📣 Cuéntale al mundo: con un hosting sólido tendrás su atención.",
    "30) 📱 Administra tu servidor desde cualquier parte, hasta la playa.",
    "31) 🌟 Planes personalizados: solo pagas por lo que realmente usas.",
    "32) 🔥 Alimenta tu servidor con la fuerza de mil soles.",
    "33) 🎭 Dile adiós al drama de caídas imprevistas.",
    "34) 🛡️ Cortafuegos y protección avanzada: cada byte a salvo.",
    "35) 🎙️ Un hosting que escucha tus necesidades y se adapta.",
    "36) 📡 Estado impecable: te informamos si hay alguna actualización.",
    "37) ⚡ Inyección de energía a tu web: performance multiplicado.",
    "38) 👾 Servidores listos para e-sports: domina al contrincante.",
    "39) 🛠️ Ajusta tu hosting sin estrés: el panel es muy amigable.",
    "40) 💀 Olvídate del temor a caídas: con TK-HOST vivirás tranquilo.",
    "41) 🚀 Sube hasta la estratosfera con nuestro hosting ultrarrápido.",
    "42) 🤖 Automatiza procesos, libera tu mente para crear más.",
    "43) 🌐 Tu página, tu identidad: dale una casa digna.",
    "44) 🛠️ Dar soporte es nuestra pasión, tu éxito nos motiva.",
    "45) 📡 Semáforo siempre en verde: tu web no conocerá el rojo.",
    "46) 🎉 Celebra cada visita: con TK-HOST no habrá interrupciones.",
    "47) 🔌 Bloqueamos desconexiones, abrimos oportunidades.",
    "48) 📊 Gráficas de rendimiento: los números hablan por ti.",
    "49) 🔥 Sube el termostato del rendimiento y quema a la competencia.",
    "50) 💰 Inversión inteligente: hosting que se amortiza solo.",
    "51) 🖥️ Tu puerta de entrada a la red: TK-HOST da la llave.",
    "52) 🎮 Lan parties virtuales sin lag: un sueño cumplido.",
    "53) 📦 Respaldos automáticos: no pierdas ni un bit.",
    "54) 🔧 Herramientas listas para devs: plugin, base de datos y más.",
    "55) 🏆 Si quieres destacar, apóyate en un equipo ganador.",
    "56) 🛒 Carrito de compras veloz: no espantes a tus clientes.",
    "57) 💎 Experiencia premium para emprendedores con clase.",
    "58) 🌟 Ilumina tu marca: un hosting con uptime real.",
    "59) 📈 SEO friendly: un sitio rápido sube peldaños en Google.",
    "60) 🔌 Lanza tu web sin tirar de la palanca errónea.",
    "61) 💡 El mejor momento para emprender fue ayer, el segundo mejor es con nosotros.",
    "62) 🔒 Protectores en guardia: contraseñas, SSL, blindaje total.",
    "63) 🎯 Enfócate en tu negocio: nosotros lo mantenemos en línea.",
    "64) 🌌 El universo digital es infinito: aprovecha cada rincón.",
    "65) 🌍 Data centers distribuidos: latencia baja en todo el globo.",
    "66) 🤑 Pack de bienvenida: aprovecha descuentos de temporada.",
    "67) 👑 Trato real, soporte de la realeza en cada detalle.",
    "68) 📣 Anuncia tu marca con seguridad y estabilidad.",
    "69) 📱 Control total en tu smartphone: no hay excusa para no revisar.",
    "70) 🌟 Estabilidad meteórica, brilla sin interrupciones.",
    "71) 🔥 Evita la congelación de tu web: mantenla candente.",
    "72) 🎭 Libre de dramas, atención 100% profesional.",
    "73) 🛡️ Seguridad anti-ataques DDoS: no habrá trolls que te tumben.",
    "74) 🎙️ Soporte humano: robots programados para servirte.",
    "75) 📡 Actualizaciones rápidas, cero tiempos de inactividad prolongados.",
    "76) ⚡ Alta tensión de velocidad: tus usuarios te lo agradecerán.",
    "77) 👾 Perfecto para servidores de Minecraft: latencia mínima.",
    "78) 🛠️ Ajustable para cualquier framework: tu stack favorito encaja aquí.",
    "79) 💀 Un hosting inmortal, no conoce la palabra 'downtime'.",
    "80) 🚀 Abandona la tierra y emprende tu viaje al éxito digital.",
    "81) 🤖 Integraciones con bots, APIs, microservicios, ¡todo en uno!",
    "82) 🌐 Conectividad robusta, tu web estará en todos los continentes.",
    "83) 🛠️ Contrata, sube tus archivos y listo: hosting sin complicaciones.",
    "84) 📡 Vigila tu uptime con nuestros informes en tiempo real.",
    "85) 🎉 Cada suscripción es una fiesta, únete y triunfa.",
    "86) 🔌 Olvida los cortes, esto es un servicio estable de verdad.",
    "87) 📊 Observa el crecimiento en tus métricas: la solidez de tu hosting influye.",
    "88) 🔥 Servidores potentes, un verdadero infierno para la competencia.",
    "89) 💰 Mejora tu ROI: lo que pagas se regresa en beneficios.",
    "90) 🖥️ Herramientas profesionales para administradores avanzados.",
    "91) 🎮 Ajustes especializados para gaming: sin lag, sin trampas.",
    "92) 📦 Espacio de sobra para tus videos, imágenes y bases de datos.",
    "93) 🔧 Panel de control con un clic para instalar CMS populares.",
    "94) 🏆 Líder en soporte: resolvemos tickets en tiempo récord.",
    "95) 🛒 Un par de clics y tu hosting estará activo: simple y directo.",
    "96) 💎 Distinción y elegancia: tu marca reflejará confiabilidad.",
    "97) 🌟 Con TK-HOST, la perseverancia se convierte en éxito online.",
    "98) 📈 Mejor rendimiento equivale a más clientes satisfechos.",
    "99) 🔌 Mantenemos tus apps encendidas: ni un segundo offline.",
    "100) 💡 Consumo de recursos optimizado: aprovecha cada CPU.",
    "101) 🔒 Certificados SSL: porque la seguridad no es opcional.",
    "102) 🎯 Claridad de configuración: no te pierdas en manuales enormes.",
    "103) 🌌 Abre tu web al infinito y más allá.",
    "104) 🌍 Servidores ecológicos: minimizamos la huella de carbono.",
    "105) 🤑 Descuentos estacionales: aprovecha y ahorra para reinvertir.",
    "106) 👑 Para proyectos grandes y pequeños: hay un plan para ti.",
    "107) 📣 Haz ruido, tu web nunca pasará desapercibida.",
    "108) 📱 Administra en móviles, tablets, ¡hasta en tu smartwatch!",
    "109) 🌟 Brilla ante tus clientes: hosting que impacta.",
    "110) 🔥 Arrasa con la competencia con la velocidad que mereces.",
    "111) 🎭 Evita sorpresas: soporte amigable y transparente.",
    "112) 🛡️ Políticas anti-malware: cuidamos tu reputación online.",
    "113) 🎙️ Escuchamos tus ideas: cada sugerencia cuenta.",
    "114) 📡 Sin límites de tráfico: deja que miles te visiten.",
    "115) ⚡ Picos de visitas no te tumbarán: infraestructura robusta.",
    "116) 👾 Compatible con servidores de Discord: bots sin latencia.",
    "117) 🛠️ Toolbox avanzada: crea, testea y despliega en el mismo lugar.",
    "118) 💀 Miedo a la migración? Nuestro equipo te apoya al 100%.",
    "119) 🚀 Cohetes listos: un push y estás online.",
    "120) 🤖 Interfaz intuitiva: ideal para novatos y expertos.",
    "121) 🌐 Filtrado inteligente de spam y ataques: no dejes pasar amenazas.",
    "122) 🛠️ Tus sueños, nuestra misión: haremos que se cumplan.",
    "123) 📡 Firewall adaptable: se ajusta a tu tráfico y necesidades.",
    "124) 🎉 Festeja cada venta, cada visita, cada clic: tu hosting resistirá.",
    "125) 🔌 Soporte multiplataforma: corre en Linux, Windows y más.",
    "126) 📊 Métricas de conversión: entérate del crecimiento real.",
    "127) 🔥 Servidores sin sobrecarga: mantenemos el balance adecuado.",
    "128) 💰 Sin costos ocultos: lo que ves es lo que pagas.",
    "129) 🖥️ Consulta en tiempo real la estadística de tu proyecto.",
    "130) 🎮 Un ping bajísimo: ideal para los fans del PvP.",
    "131) 📦 Copias de seguridad diarias: tu información está segura.",
    "132) 🔧 Tools dev-friendly: cPanel, PHPmyAdmin, auto-installer, ¡y más!",
    "133) 🏆 Encabezamos el ranking en uptime: la constancia es clave.",
    "134) 🛒 Mayor flexibilidad de pago: elige la forma que prefieras.",
    "135) 💎 Rendimiento pulido: no habrá bordes ásperos en tu web.",
    "136) 🌟 Soporte humano, sin chatbots fríos e impersonales.",
    "137) 📈 Plan de escalado: no te quedes chico al crecer.",
    "138) 🔌 Sin interrupciones: mantenimiento programado y veloz.",
    "139) 💡 Aprende en nuestro blog: tutoriales y guías gratis.",
    "140) 🔒 Doble verificación: protegiendo tu cuenta de intrusos.",
    "141) 🎯 Meta: tu satisfacción. Somos obstinados para lograrlo.",
    "142) 🌌 Un horizonte infinito de posibilidades digitales.",
    "143) 🌍 Cobertura mundial: sirve a clientes en cualquier región.",
    "144) 🤑 Recupera tu inversión en poco tiempo con un hosting eficiente.",
    "145) 👑 Una corona para tu negocio online: la calidad es el rey.",
    "146) 📣 Promociona sin límites, soportamos alto tráfico.",
    "147) 📱 Panel responsive, gestión sin ataduras de escritorio.",
    "148) 🌟 Forja tu reputación online con un hosting impecable.",
    "149) 🔥 ¿Fallas? En TK-HOST ni las conocemos.",
    "150) 🎭 Mantén la calma: nuestro equipo arregla cualquier caída en minutos.",
    "151) 🛡️ Anti-virus integrado: mantiene a raya las amenazas.",
    "152) 🎙️ Di lo que piensas: testimonios de clientes nos avalan.",
    "153) 📡 Infraestructura escalable: crecemos contigo.",
    "154) ⚡ Carga tus páginas a la velocidad del rayo.",
    "155) 👾 Base de datos a prueba de bombardeos intensivos.",
    "156) 🛠️ Integra tus pipelines de CI/CD sin dolor de cabeza.",
    "157) 💀 Se acabó el terror de que tu web caiga sin previo aviso.",
    "158) 🚀 Prepárate para despegar: el cielo no es el límite.",
    "159) 🤖 Integramos tecnologías emergentes: IA, VR, AR y más.",
    "160) 🌐 Dirige tu orquesta digital: hosting confiable y armónico.",
    "161) 🛠️ Tu e-commerce seguro: no pierdas ventas por errores.",
    "162) 📡 Salta a la nube: nosotros te agarramos si cae la conexión.",
    "163) 🎉 Cada día es un logro: mantenemos viva tu web sin dramas.",
    "164) 🔌 Respaldo inmediato: tu página jamás quedará desprotegida.",
    "165) 📊 Audita tu rendimiento: te damos las mejores herramientas.",
    "166) 🔥 Desafía a la competencia con un hosting inquebrantable.",
    "167) 💰 Calidad-precio insuperable: tu dinero bien invertido.",
    "168) 🖥️ Panel personalizable: ponle tu sello personal.",
    "169) 🎮 Salas de juego online fluidas: baja latencia garantizada.",
    "170) 📦 No te limites, expandimos tu almacenamiento cuando quieras.",
    "171) 🔧 Resolvemos bugs con la velocidad del rayo.",
    "172) 🏆 Máximo prestigio: tu web reflejará seriedad y profesionalismo.",
    "173) 🛒 Múltiples pasarelas de pago para tu tienda online.",
    "174) 💎 Destaca entre millones: un hosting premium para un proyecto top.",
    "175) 🌟 Gana la confianza de tus usuarios con nuestro uptime real.",
    "176) 📈 Haz crecer tus leads con tiempos de respuesta óptimos.",
    "177) 🔌 Conectividad de primer nivel: no sufras microcortes.",
    "178) 💡 Innovación constante: siempre mejorando nuestras infraestructuras.",
    "179) 🔒 Subdominios y certificados, todo en un solo lugar.",
    "180) 🎯 Tu meta es la nuestra: un hosting que se adapta a tus planes.",
    "181) 🌌 Explora nuevos horizontes de desarrollo con nuestra plataforma.",
    "182) 🌍 Conectado a redes de alta velocidad: milisegundos vitales.",
    "183) 🤑 Ganancias duplicadas: un sitio rápido vende más.",
    "184) 👑 Conviértete en el rey del nicho: hosting de élite.",
    "185) 📣 Difunde sin límites: correos transaccionales y marketing.",
    "186) 📱 Gestiona tu hosting en el tren, en el parque, en cualquier lugar.",
    "187) 🌟 Tu éxito es nuestro: celebramos tus logros online.",
    "188) 🔥 Mantén a raya la competencia con rendimiento implacable.",
    "189) 🎭 Sin dramas: cierra los tickets con soluciones definitivas.",
    "190) 🛡️ Espacio blindado: ni hackers ni virus podrán entrar.",
    "191) 🎙️ Soporte en tu idioma, atención amistosa y efectiva.",
    "192) 📡 Sin sobresaltos: avisos de mantenimiento con suficiente antelación.",
    "193) ⚡ Hardwares de última generación: un Ferrari bajo el capó.",
    "194) 👾 Hostea bots de juego, foros, blogs: lo que imagines.",
    "195) 🛠️ Subida de archivos masiva: no te limites a lo pequeño.",
    "196) 💀 Conserva la calma: este hosting no muere así de fácil.",
    "197) 🚀 El impulso que te faltaba para despegar en el mundo digital.",
    "198) 🤖 Scripts automatizados: todo fluye sin tu intervención.",
    "199) 🌐 Firmeza total: tus visitantes merecen una experiencia sólida.",
    "200) 🛠️ Ajusta parámetros en segundos: el poder está en tus manos."
  ]

  // Seleccionamos una frase al azar
  const randomResponse = responses[Math.floor(Math.random() * responses.length)]

  // 3) Construimos el texto final con un formato tipo “welcome”
  // (pero adaptado a E-S-T-A-D-O).
  const text = `
*✦━── ──━✦ \`E-S-T-A-D-O\` ✦━── ──━✦*

╭── • ✧ • ✧ • ✧ • ✧ • ✧ •
│ 🔍 *Estado del servicio:*
│ ${randomResponse}
╰── • ✧ • ✧ • ✧ • ✧ • ✧ •

> Consulta aquí:
> https://dash.tk-joanhost.com/home
`.trim()

  // 4) Enviamos la imagen aleatoria y el mensaje con la frase
  await conn.sendFile(m.chat, randomImageUrl, 'estado.jpg', text, m)
}

// Activamos este handler con los comandos .estado y .s
handler.command = ['estado', 's']
handler.tags = ['estado']
handler.help = ['estado', 's']

export default handler
